#!/bin/sh

module load Nextflow/21.10.6
module load Singularity/3.6.4

WORK=work

export NXF_SINGULARITY_CACHEDIR=$WORK/singularity

nextflow run main.nf \
	-params-file params.yml \
	-work-dir $WORK \
	-resume

